"""empty message

Revision ID: 112a18ddc7b0
Revises: a970c6b2abcc
Create Date: 2023-12-20 15:09:11.157186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '112a18ddc7b0'
down_revision = 'a970c6b2abcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_orders_user_id', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
